---
title: "Лабораторная работа №7"
editor: 
  markdown: 
    wrap: 72
---

# Атаки на личность в соцсетях и воровство аккаунтов

> *Цифровая личность*- совокупность информации, которую можно собрать о
> человеке из открытых источников (соц. сети, общедоступные источники).

О пользователе можно узнать практически любую информацию вплоть до
медицинских анализов и использовать ее в своих целях.

### Виды мошенничества в соц.сетях:

-   Фишинг

-   Взлом аккаунтов

-   Шантаж

-   Копирование профилей

Если к Вам добавляется друг со второго такого же аккаунта или пишет
спустя долго время и просит денег, то стоит задуматься и проверить,
является ли он тем, за кого себя выдает.

### Цели похищения аккаунтов:

-   Рассылка спама, фишинговых сообщений
-   Сбор денег

У злоумышленников одна цель - **деньги**.

[Совет*:* сохранять спокойствие, не принимать решения на эмоциях. В
случае возникновения какой-либо ситуации взять паузу и все обдумать,
оценить обстановку.]{.underline}

Ваша цифровая личность - ваше отражение, вся информация о вас, то, как
вы будете реагировать в той или иной ситуации, ваши привычки и
поведение.
